[window]
padding = { x = 25, y = 25 }

[font]
normal = { family = "Comic Mono", style = "normal"}
bold = { family = "Comic Mono", style = "bold"}
size = 28
offset = { y = 3 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "always" }
vi_mode_style = { shape = "Underline", blinking = "always" }
blink_interval = 350
blink_timeout = 20

[scrolling]
history = 100000

[keyboard]
bindings = [
  #{ key = "u", mods = "Super", action = "ScrollLineUp" },
  #{ key = "l", mods = "Super", action = "ScrollLineDown" },
  { key = "h", mods = "Super", action = "Paste" },
  { key = "-", mods = "Super", action = "DecreaseFontSize" },
  { key = "=", mods = "Super", action = "IncreaseFontSize" },
  { key = "y", mods = "Super", action = "ToggleViMode" },

  { key = "e", mode = "Vi|~Search", action = "Up" },
  { key = "n", mode = "Vi|~Search", action = "Down" },
  { key = "m", mode = "Vi|~Search", action = "Left" },
  { key = "i", mode = "Vi|~Search", action = "Right" },
  { key = "e", mods = "Shift", mode = "Vi|~Search", action = "SearchPrevious" },
  { key = "n", mods = "Shift", mode = "Vi|~Search", action = "SearchNext" },
  { key = "q", mode = "Vi", action = "WordLeft" },

]

# Firewatch Light - Alacritty Theme
# Based on the Vim theme "two-firewatch" by Ramzi Akremi


[colors.cursor]
text = "#FAF8F5"
cursor = "#d65d0e"
#cursor = "#b16286"


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
